[colors.bright]
black = "#4b565c"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.normal]
black = "#4b565c"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.primary]
foreground = "#d3c6aa"
background = "#262626"

[cursor.style]
blinking = "On"
shape = "Block"

[cursor.vi_mode_style]
shape = "Underline"
blinking = "Off"

[font]
size = 7.7

[font.bold]
family = "monospace"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[font.offset]
x = -1
y = -1

#[schemes.everforest_dark_hard.bright]
#black = "#4b565c"
#blue = "#7fbbb3"
#cyan = "#83c092"
#green = "#a7c080"
#magenta = "#d699b6"
#red = "#e67e80"
#white = "#d3c6aa"
#yellow = "#dbbc7f"
#
#[schemes.everforest_dark_hard.normal]
#black = "#4b565c"
#blue = "#7fbbb3"
#cyan = "#83c092"
#green = "#a7c080"
#magenta = "#d699b6"
#red = "#e67e80"
#white = "#d3c6aa"
#yellow = "#dbbc7f"
#
#[schemes.everforest_dark_hard.primary]
#foreground = "#d3c6aa"
#
#[schemes.everforest_dark_medium.bright]
#black = "#4b565c"
#blue = "#7fbbb3"
#cyan = "#83c092"
#green = "#a7c080"
#magenta = "#d699b6"
#red = "#e67e80"
#white = "#d3c6aa"
#yellow = "#dbbc7f"
#
#[schemes.everforest_dark_medium.normal]
#black = "#4b565c"
#blue = "#7fbbb3"
#cyan = "#83c092"
#green = "#a7c080"
#magenta = "#d699b6"
#red = "#e67e80"
#white = "#d3c6aa"
#yellow = "#dbbc7f"
#
#[schemes.everforest_dark_medium.primary]
#foreground = "#d3c6aa"
#
#[schemes.everforest_dark_soft.bright]
#black = "#4b565c"
#blue = "#7fbbb3"
#cyan = "#83c092"
#green = "#a7c080"
#magenta = "#d699b6"
#red = "#e67e80"
#white = "#d3c6aa"
#yellow = "#dbbc7f"
#
#[schemes.everforest_dark_soft.normal]
#black = "#4b565c"
#blue = "#7fbbb3"
#cyan = "#83c092"
#green = "#a7c080"
#magenta = "#d699b6"
#red = "#e67e80"
#white = "#d3c6aa"
#yellow = "#dbbc7f"
#
#[schemes.everforest_dark_soft.primary]
#foreground = "#d3c6aa"
#
#[schemes.everforest_light_hard.bright]
#black = "#5c6a72"
#blue = "#3a94c5"
#cyan = "#35a77c"
#green = "#8da101"
#magenta = "#df69ba"
#red = "#f85552"
#white = "#dfddc8"
#yellow = "#dfa000"
#
#[schemes.everforest_light_hard.normal]
#black = "#5c6a72"
#blue = "#3a94c5"
#cyan = "#35a77c"
#green = "#8da101"
#magenta = "#df69ba"
#red = "#f85552"
#white = "#dfddc8"
#yellow = "#dfa000"
#
#[schemes.everforest_light_hard.primary]
#background = "#fff9e8"
#foreground = "#5c6a72"
#
#[schemes.everforest_light_medium.bright]
#black = "#5c6a72"
#blue = "#3a94c5"
#cyan = "#35a77c"
#green = "#8da101"
#magenta = "#df69ba"
#red = "#f85552"
#white = "#dfddc8"
#yellow = "#dfa000"
#
#[schemes.everforest_light_medium.normal]
#black = "#5c6a72"
#blue = "#3a94c5"
#cyan = "#35a77c"
#green = "#8da101"
#magenta = "#df69ba"
#red = "#f85552"
#white = "#dfddc8"
#yellow = "#dfa000"
#
#[schemes.everforest_light_medium.primary]
#background = "#fdf6e3"
#foreground = "#5c6a72"
#
#[schemes.everforest_light_soft.bright]
#black = "#5c6a72"
#blue = "#3a94c5"
#cyan = "#35a77c"
#green = "#8da101"
#magenta = "#df69ba"
#red = "#f85552"
#white = "#dfddc8"
#yellow = "#dfa000"
#
#[schemes.everforest_light_soft.normal]
#black = "#5c6a72"
#blue = "#3a94c5"
#cyan = "#35a77c"
#green = "#8da101"
#magenta = "#df69ba"
#red = "#f85552"
#white = "#dfddc8"
#yellow = "#dfa000"
#
#[schemes.everforest_light_soft.primary]
#background = "#f8f0dc"
#foreground = "#5c6a72"

#[window]
#gtk_theme_variant = "None"

[window.padding]
x = 0
y = 0
