import = ["~/.config/alacritty/themes/dracula.toml"]

#[colors.bright]
#black = "#4b565c"
#blue = "#7fbbb3"
#cyan = "#83c092"
#green = "#a7c080"
#magenta = "#d699b6"
#red = "#e67e80"
#white = "#d3c6aa"
#yellow = "#dbbc7f"

#[colors.normal]
#black = "#4b565c"
#blue = "#7fbbb3"
#cyan = "#83c092"
#green = "#a7c080"
#magenta = "#d699b6"
#red = "#e67e80"
#white = "#d3c6aa"
#yellow = "#dbbc7f"

#[colors.primary]
#foreground = "#d3c6aa"
#background = "#262626"

[cursor.style]
blinking = "On"
shape = "Block"

[cursor.vi_mode_style]
shape = "Underline"
blinking = "Off"

[font]
size = 7.7

[font.bold]
family = "monospace"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[font.offset]
x = -1
y = -1

[window.padding]
x = 0
y = 0

