import = ["~/.config/alacritty/themes/srcery.toml"]

[cursor.style]
blinking = "On"
shape = "Block"

[cursor.vi_mode_style]
shape = "Underline"
blinking = "Off"

[font]
size = 7.7

[font.bold]
family = "monospace"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[font.offset]
x = -1
y = -1

[window.padding]
x = 0
y = 0
